services:
  - type: web
    name: n8n-meme-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_SECURE_COOKIE
        value: false
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: N8N_ENCRYPTION_KEY
        value: 5220a0f1104c53ddd34d7c4ca6e4aa62
